name: PRE-COMMIT

on:
  push:

jobs:
  BUILD:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: CHECK BRANCH NAME
        working-directory: ./hooks
        run :
          echo $(git rev-parse --abbrev-ref HEAD)
          chmod +x pre-commit
          bash pre-commit

