name: PRE-COMMIT

on:
  push:

jobs:
  BUILD:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: CHECK BRANCH NAME
        working-directory: ./hooks
        run :
          echo Running script without sh ending
          chmod +x ./pre-commit.sh
          ./pre-commit.sh

