name: GET_RANDOM_NUMBER

on:
  workflow_call:
    outputs:
      number:
        description: "RANDOM NUMBER"
        value: ${{ jobs.GENERATE_RUNDOM_NUMBER.outputs.output }}

jobs:
  GENERATE_RUNDOM_NUMBER:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.random_number.outputs.random_number }}

    steps:

      - name: GENERATE OUTPUT
        id: random_number
        run: |
          echo "random_number=$RANDOM" >> $GITHUB_OUTPUT

      - name: PRINT NUMBER
        run: |
            SUMMARY=| Value |\n| ${{ steps.random_number.outputs.random_number }} |'
            echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
