name: MATRIX

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  GENERATE_MATRIX:
    uses: ./.github/workflows/generate-folders-matrix-reusable.yml

  RUN_WITH_MATRIX:
    needs: GENERATE_MATRIX
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: ${{ fromJSON(needs.GENERATE_MATRIX.outputs.matrix) }}
      fail-fast: false
      max-parallel: 2

    steps:
      - name: SLEEP
        run: |
          sleep 5s

      - name: PRINTING ${{ matrix.folder }} FOLDER
        run: | 
          echo ${{ matrix.folder }}
