name: PR-VERIFICATION

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  BUILD:

    permissions:
      checks: write

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:

      - name: Verify Branch Name
        run: |
          
            PR_BRANCH=$(echo "${{ github.head_ref }}" | cut -d '/' -f 2)
            
            BRANCH_PATTERN="test/[A-Za-z0-9]*"
            
            if [[ ! "$PR_BRANCH" =~ $BRANCH_PATTERN ]]; then
              echo "Error: Branch name '$PR_BRANCH' does not match the required pattern."
              exit 1
            else
              echo "Branch name '$PR_BRANCH' is valid."
            fi

      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: CHECK BRANCH NAME
        working-directory: ./hooks
        run : |
          chmod +x ./pre-commit
          ./pre-commit

      - name: EXECUTE TESTS
        run : |
          ./gradlew clean test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
