name: REUSABLE-WORKFLOW
on:
  workflow_call:
    inputs:
      java_version:
        default: 17
        type: string
      java_distribution:
        default: temurin
        type: string

jobs:
  BUILD:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:

      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP JAVA
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java_distribution }}
          java-version: ${{ inputs.java_version }}

      - name: HELLO WORLD
        run: |
          run: |
            SUMMARY='### Hello world! :rocket:'
            echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

