name: DEMO_WORKFLOW

on:
  workflow_dispatch:

jobs:

  SETUP:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit

  RANDOM_NUMBER:
    needs: [SETUP]
    uses: ./.github/workflows/get-random-number.yml

  FINISH:

    needs: [RANDOM_NUMBER]

    runs-on:
      - ubuntu-latest

    steps:
      - name: SETUP JQ
        uses: dcarbone/install-jq-action@v2.1.0

      - name: PRINT NUMBER
        run: |
          echo ${{ needs.RANDOM_NUMBER.outputs.number }}

      - name: BUILD ENV SPECS
        run: |
          ip=$(curl -s -k https://ipinfo.io | jq -r '.ip')
          echo -e " | HOST NAME | $HOSTNAME | \n | IP | \n | $ip " >> $GITHUB_STEP_SUMMARY
    

  
