name: TEST

on:
  workflow_dispatch:

jobs:

  SETUP:
    uses: ./.github/workflows/reusable-workflow.yml
  RANDOM_NUMBER:
    needs: [SETUP]
    uses: ./.github/workflows/get-rundom-number.yml
  FINISH:
    needs: [RANDOM_NUMBER]
    runs-on:
      - ubuntu-latest
    steps:
      - name: PRINT NUMBER
        run: |
          echo ${{ needs.RANDOM_NUMBER.outputs.number }}
    

  
